version: 2
updates:

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "development"
    ignore:
    - dependency-name: "facebook/graph-sdk*" 
    schedule:
      interval: "weekly"
