name: Build Artifact

on: [push, pull_request]

jobs: 
  setup-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          tools: phpcs, phpcbf
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.18'
      - run: |
          node -v
          npm -v
      - name: Install npm dependencies
        run: |
          npm install
          phpcs -i
      #grunt local
      - name: Install composer
        run: composer install --prefer-dist --no-progress
      - run: |
            grunt local
            phpcs -i



 