name : Test PHP

on: [push, pull_request]

jobs:
  code-sniff:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout source code
         uses: actions/checkout@v2
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
         with: 
          php-version: '7.2'
          tools: phpcs
       - name: Install composer
         run: composer install --prefer-dist --no-progress
       - name: List PHP CS standards
         run: phpcs -i
       - name: PHP LINT
         run: composer run lint

  php-unit: 
    #needs: code-sniff 
    runs-on: ubuntu-latest
    steps:
     - name: Checkout source code
       uses: actions/checkout@v2
     - name: Install composer
     - name: Setup PHP
       uses: shivammathur/setup-php@v2
       with:
          php-version: '7.2'
          # tools: phpcs
       run: composer install --prefer-dist --no-progress
     - name: Run PHP Unit
       run: composer run test