name : Test PHP TEST

on: [push, pull_request]

jobs:
  test-terminal:
    runs-on: ubuntu-latest
    steps:
      - run: cat /etc/os-release
  test-terminal-2: 
    runs-on: ubuntu-18.04
    steps:
     - run: |
            grep '^VERSION' /etc/os-release
            egrep '^(VERSION|NAME)=' /etc/os-release